### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by skhotta** [Afterglow/chef-reboot#3]
Steps:
added to the runlist
recipe[chef-reboot]"

Added to another recipe of another cookbook 
node[:reboot][:auto_reboot] = 0

I get the following error:
## NoMethodError

undefined method `[]=' for nil:NilClass

 1:  
  2:  
  3:
  4:
  5>> node[:reboot][:auto_reboot] = 0
  6:

**Comment by Afterglow** [comment]
In 3d79f00 i've added a default attribute which sets reboot to 0. In the original cookbook the attribute was confusingly node[:bootstrap][:auto_reboot] due to legacy reasons. I've updated it all to be node[:reboot][:auto_reboot] now. The commit also reverses the default behaviour from auto_reboot = 1 to auto_reboot = 0  which conforms more to the principle of least surprise.

All in all if you switched to 1.0.0 of the cookbook you should find this problem goes away. You should be able to add `recipe[reboot]` to your run_list and then set node[:reboot][:auto_reboot] to 1 in order to trigger a reboot. I don't have any way to test this right now so YMMV I wonder if there wouldn't be a better way to handle this generally.
